import{a as p,S as b,i as w}from"./assets/vendor-D0cagnvz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const L="48924645-79e9b00d1f962ef58b63a0249";async function h(o,t=1,a=40){const s=`https://pixabay.com/api/?key=${L}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${a}&page=${t}`;try{const e=await p.get(s);if(e.data.hits.length===0)throw new Error("No images found");return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){throw console.error("Error fetching images:",e),e}}function g(o,t=!1){const a=document.querySelector(".gallery");t||(a.innerHTML=""),o.forEach(e=>{const r=`
      <div class="photo-card">
        <a href="${e.largeImageURL}" class="gallery__item">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery__image" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </div>
    `;a.insertAdjacentHTML("beforeend",r)}),new b(".gallery a").refresh()}function u(o){w.error({title:"Error",message:o})}function m(){document.querySelector(".loading").classList.remove("hidden")}function y(){document.querySelector(".loading").classList.add("hidden")}function v(){document.querySelector(".gallery").innerHTML=""}function S(){var a;const t=((a=document.querySelector(".gallery").firstElementChild)==null?void 0:a.getBoundingClientRect().height)||0;window.scrollBy({top:t*2,behavior:"smooth"})}const q=document.querySelector("#search-form"),f=document.querySelector(".search-input"),c=document.querySelector("#load-more");let i="",n=1;const l=40;q.addEventListener("submit",async o=>{if(o.preventDefault(),i=f.value.trim(),!i){alert("Please enter a search term.");return}n=1,c.classList.add("hidden"),v();try{m();const{images:t,totalHits:a}=await h(i,n,l);g(t),f.value="",a>l&&c.classList.remove("hidden")}catch{u("Something went wrong! Please try again later.")}finally{y()}});c.addEventListener("click",async()=>{n++;try{m();const{images:o,totalHits:t}=await h(i,n,l);g(o,!0),S(),n*l>=t&&(c.classList.add("hidden"),u("We're sorry, but you've reached the end of search results."))}catch{u("Something went wrong! Please try again later.")}finally{y()}});
//# sourceMappingURL=index.js.map
