import{a as p,S as b,i as w}from"./assets/vendor-D0cagnvz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const L="48924645-79e9b00d1f962ef58b63a0249";async function h(o,t=1,s=40){const a=`https://pixabay.com/api/?key=${L}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${s}&page=${t}`;try{const e=await p.get(a);if(e.data.hits.length===0)throw new Error("No images found");return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){throw console.error("Error fetching images:",e),e}}function g(o,t=!1){const s=document.querySelector(".gallery");t||(s.innerHTML=""),o.forEach(e=>{const r=`
      <div class="photo-card">
        <a href="${e.largeImageURL}" class="gallery__item">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery__image" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </div>
    `;s.insertAdjacentHTML("beforeend",r)}),new b(".gallery a").refresh()}function u(o){w.error({title:"Error",message:o})}function m(){document.querySelector(".loading").classList.remove("hidden")}function y(){document.querySelector(".loading").classList.add("hidden")}function f(){document.querySelector(".gallery").innerHTML=""}function v(){var s;const t=((s=document.querySelector(".gallery").firstElementChild)==null?void 0:s.getBoundingClientRect().height)||0;window.scrollBy({top:t*2,behavior:"smooth"})}const S=document.querySelector("#search-form"),q=document.querySelector(".search-input"),c=document.querySelector("#load-more");let i="",n=1;const l=40;S.addEventListener("submit",async o=>{if(o.preventDefault(),i=q.value.trim(),n=1,c.classList.add("hidden"),!i){alert("Please enter a search term.");return}try{m(),f();const{images:t,totalHits:s}=await h(i,n,l);g(t),s>l&&c.classList.remove("hidden")}catch{f(),u("Something went wrong! Please try again later.")}finally{y()}});c.addEventListener("click",async()=>{n++;try{m();const{images:o,totalHits:t}=await h(i,n,l);g(o,!0),v(),n*l>=t&&(c.classList.add("hidden"),u("We're sorry, but you've reached the end of search results."))}catch{u("Something went wrong! Please try again later.")}finally{y()}});
//# sourceMappingURL=index.js.map
